server:
  port: 8062
  forward-headers-strategy: framework
  
app:
  public-key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6Q2lW4kepLJdZ4kauXed
      GNyjU9zS7K3BkvjVtDvuVUF46RiCoRSyCYIF7+0jKZVCxPCSslRnId9vavbsG2xp
      WEIURWkNiCAP0lKPm+hemQfjLIM1ZsUi8BU5Mzojp4vJW7MCC/OR9UKg1en5B1R8
      Wg0tP3/7ub5X0YtMZtUf1DrnGaGnbHMS1Ka5+AB+qfh9l9IpTr5qzHQJooUYPp2k
      qfO5B0Q17cAX05mktjQrK/JTKo7GkyK8NDc+oByL5aopzf4nZj+mk+L7O6LVHpKN
      d7OyFzQJG01nwNL1y6qWsndtgI02aRV1eRIQQBmg1n+ebvi/d25UniX37FT6rcR+
      BwIDAQAB
      -----END PUBLIC KEY-----
  
security:
  oauth2:
    client:
      clientId: sathish_ch
      clientSecret: password
      accessTokenUri: ${SECURITY-SERVICE-ENDPOINT}/oauth/token
      user-authorization-uri: ${SECURITY-SERVICE-ENDPOINT}/oauth/authorize
    resource:
      token-info-uri: ${SECURITY-SERVICE-ENDPOINT}/oauth/check_token
      user-info-uri:  ${SECURITY-SERVICE-ENDPOINT}/userinfo
    resourceserver:
      jwt:
        issuer-uri: ${SECURITY-SERVICE-ENDPOINT}/oauth/token

spring:
  datasource:
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    url: ${JDBC_CONNECTION_STRING}
    hikari:
      minimum-idle: 25
      maximum-pool-size: 200
      idle-timeout: 30000
      pool-name: SpringBootJPAHikariCP
      connection-timeout: 30000
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        
#    hibernate:
#      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  mail:
    host: smtp.office365.com
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    protocol: smtp
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

springfox:
  documentation:
    auto-startup: false
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE